// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Bypass import.meta.env entirely for Lovable deployment
const SUPABASE_URL = "https://vtufpmuhtonoyerzmyqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_E1XRUxHh0NOuboqkrOnjVQ_K3F0ZJd_";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});